### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by Kvetter** [JoachimEChristensen/UFOReport#1]
Overview: 5
  - Mangler strukter med f.eks flere overskrift for at opdele afsnit
  - Jeres "forklaring/bevis" for at indeksering er godt, er ikke præcist da i tester to forskellige queries i stedet for at bruge den samme query, med og uden indeksering

**Comment by JoachimEChristensen** [comment]
Overskrifter sat på til at give bedre overblik

Indeksering på den samme tabel med et query uden index og et andet query med index gør ingen forskel i forhold til den samme query med eller uden index.
