### ISSUE TITLE
Design Criteria, Sample Calc and Simulations

### ISSUE THREAD

**Issue by Kvetter** [JoachimEChristensen/UFOReport#5]
Design Criteria, Sample Calc and Simulations: 2
- Jeres "eksempel" stemmer ikke overens med hvad i siger. Først så kan i ikke sammenligne to forskellige queries og så antage at det er indekseringen som gør forskellen. Hvis i skal teste effektiviteten af indeksering skal i gøre det ved brug af den samme query.
- Derudover skifter i også mening i forhold til jeres diagram, hvilke query som er indekseret "First, we ran a query on a large table without any indexes. " og senere "The first query, which is indexed, has an easier time". Det gør at vi ikke ved hvilke resultat i er kommet frem til og derfor ikke kan se noget "bevis" for jeres konklusion

**Comment by JoachimEChristensen** [comment]
Det er muligt at sammenligne to queries på den samme tabel, selv om at kun en af værdierne er blevet indekseret.

Querierne er blevet refereret til i den rigtige rækkefølge nu.
